#!/usr/bin/env bash
# configures a new Ubuntu machine 
sudo apt-get -y update
sudo apt-get -y install nginx
#sed -i 's/listen 80 default_server/listen 80/' /etc/nginx/sites-available/default
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
