#!/usr/bin/env bash
#commands to automatically configure a Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
#sed -i 's/listen 80 default_server/listen 80/' /etc/nginx/sites-available/default
sudo chown -R $USER:$USER /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_string="a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
