#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
service nginx restart
