#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server
apt-get -y update
apt-get install haproxy=1.6.\*

echo '
frontend sabah-alx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 363477-web-01 100.25.41.212:80
        server 363477-web-02 100.25.103.239:80
' >> /etc/haproxy/haproxy.cfg
haproxy -c -f /etc/haproxy/haproxy.cfg
service haproxy start
