#!/usr/bin/env bash
#Create a MySQL user named holberton_user, host name set to localhost and the password projectcorrection280hbtn
sudo mysql -u root -p
CREATE USER 'holberton_user'@'localhost' IDENTIFIED BY 'projectcorrection280hbtn';
GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;
#create database
CREATE DATABASE tyrell_corp;
USE tyrell_corp;
#create table
CREATE TABLE nexus6 ( id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) );
INSERT INTO nexus6 (name) VALUES ('Sabah');
GRANT ALL PRIVILEGES ON tyrell_corp.* TO 'holberton_user'@'localhost';
#create a new user for the replica server
CREATE USER 'replica_user'@'%' IDENTIFIED BY 'projectcorrection280hbtn';
GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';
GRANT SELECT ON mysql.user TO 'holberton_user'@'localhost';
FLUSH PRIVILEGES;
