#!/usr/bin/env bash
#Configure ufw to blocks all incoming traffic, except ports:22 (SSH), 443 (HTTPS SSL), 80 (HTTP)
ufw default deny incoming
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
ufw enable
