#!/usr/bin/env bash
#configure nginx to running as user and listening on all active IPs on port 8080
pkill apache2
sudo adduser --system --no-create-home nginx
chown nginx:nginx /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
